
# Make using installed package
build::
	(cd rotate-square; make build)
	(cd trivial; make build)
	(cd html5canvastutorial; make build)
	(cd square; make build)
	(cd tictactoe; make build)
	(cd keyread; make build)

# Make using source
build-inplace::
	(cd rotate-square; make build-inplace)
	(cd trivial; make build-inplace)
	(cd html5canvastutorial; make build-inplace)
	(cd square; make build-inplace)
	(cd tictactoe; make build-inplace)
	(cd keyread; make build-inplace)
